added  http and https checking for server url

diff --git a/moodle-docker/bin/moodle-docker-compose b/moodle-docker/bin/moodle-docker-compose
--- a/moodle-docker/bin/moodle-docker-compose
+++ b/moodle-docker/bin/moodle-docker-compose
@@ -36,9 +36,18 @@ export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-8.1}
 if [ "$MOODLE_SERVER_SSL" == true ];
 then
   echo "Setting up SSL";
+  if [[ $MOODLE_SERVER_URL != https://* ]]; then
+    echo "Error: configuration option MOODLE_SERVER_SSL is set to TRUE, but MOODLE_SERVER_URL does not start with https://"
+    exit 1
+  fi
   dockercompose="${dockercompose} -f ${basedir}/ssl/webserver.ssl.port.yml"
   cp "${MOODLE_SERVER_SSL_CERTIFICATE_FILE}" "${basedir}/moodle-php-apache/root/etc/nginx/moodle_certificate.crt"
   cp "${MOODLE_SERVER_SSL_PRIVATE_KEY_FILE}" "${basedir}/moodle-php-apache/root/etc/nginx/moodle.key"
+else
+  if [[ $MOODLE_SERVER_URL != http://* ]]; then
+      echo "Error: configuration option MOODLE_SERVER_SSL is set to FALSE, but MOODLE_SERVER_URL does not start with http://"
+      exit 1
+    fi
 fi
 
 # Database flavour.
@@ -56,7 +65,6 @@ fi
 # Chatbot
 if [ "$PLUGIN_CHATBOT" == true ];
 then
-    echo "Installing chatbot!"
     dockercompose="${dockercompose} -f ${basedir}/chatbot.yml"
 fi
 
